[package]
name = "rust_swig"
version = "0.2.0-pre"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
description = "Tool for connecting libraries written in Rust with other languages"
license = "BSD-3-Clause"
keywords = ["swig", "java", "jni", "ffi", "cxx"]
repository = "https://github.com/Dushistov/rust_swig"
documentation = "https://docs.rs/rust_swig"
readme = "../README.md"
edition = "2018"

[[bin]]
name = "rust_swig"
path = "src/main.rs"
doc = false

[dependencies]

[dev-dependencies]

[build-dependencies]

[badges]
travis-ci = { repository = "Dushistov/rust_swig" }
appveyor = { repository = "Dushistov/rust_swig" }
