[package]
name = "rust_swig"
version = "0.0.2"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
description = "Tool for simplification of Rust usage from other languages"
license = "BSD-3-Clause"
keywords = ["swig", "java", "jni", "ffi", "wrapper"]

[dependencies]
syntex = "0.47.0"
syntex_syntax = "0.47.0"
syntex_pos = "0.47.0"
lazy_static = "0.2.2"
log = "0.3"
