[package]
name = "rust_swig"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]

[dependencies]
syntex = "0.47.0"
syntex_syntax = "0.47.0"
syntex_pos = "0.47.0"
lazy_static = "0.2.2"