[package]
name = "rust_swig_test_jni"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
build = "build.rs"

[lib]
name = "rust_swig_test_jni"
crate-type = ["cdylib"]

[dependencies]
log = "0.3"
chrono = "0.4.0"

[build-dependencies]
syntex = "0.58.1"
env_logger = "0.4.2"
bindgen = { git = "https://github.com/rust-lang-nursery/rust-bindgen", rev = "ce7e69bfbc5a6e47eb1d9ee4f0b43a5afeef0f31" }
log = "0.3"
rust_swig = { path = "../macroslib" }

