[package]
name = "rust_swig_test_jni"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
build = "build.rs"

[lib]
name = "rust_swig_test_jni"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
chrono = "0.4.0"

[build-dependencies]
env_logger = "0.5"
log = "0.4"
rust_swig = { path = "../macroslib" }

