[package]
name = "rust_swig_test_jni"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
build = "build.rs"

[lib]
name = "test"
crate-type = ["cdylib"]

[dependencies]
log = "0.3"

[build-dependencies]
syntex = "0.47.0"
env_logger = "0.3"
bindgen = {git = "https://github.com/servo/rust-bindgen", rev = "b71c7ba46b5992e00cc05d9d5788b9cecbcb6305"}
log = "0.3"

[build-dependencies.rust_swig]
path = "../macroslib"

