[package]
name = "rust_swig_test_jni"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
build = "build.rs"

[lib]
name = "rust_swig_test_jni"
crate-type = ["cdylib"]

[dependencies]
log = "0.3"

[build-dependencies]
syntex = "0.54.0"
env_logger = "0.3"
bindgen = "0.22.1"
log = "0.3"

[build-dependencies.rust_swig]
path = "../macroslib"

