dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
cache: cargo
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-set-default
      - llvm-3.9-dev
      - libclang-3.9-dev
      - python3
      - build-essential
      - valgrind
before_script:
    - export LIBCLANG_PATH=/usr/lib/llvm-3.9/lib
    - if [ "$TRAVIS_RUST_VERSION" == "beta" ]; then
          rustup component add --toolchain beta rustfmt-preview;
      fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
         export JAVA_HOME=$(/usr/libexec/java_home);
      fi
    - echo $JAVA_HOME
    - cmake --version
    - python --version
    - export TAR="boost_1_56_0.tar.gz"
    - curl -L -o $TAR http://sourceforge.net/projects/boost/files/boost/1.56.0/$TAR/download
    - tar -xzf $TAR
    - export BOOST_ROOT=$PWD/boost_1_56_0
script:
  - echo $RUSTC_WRAPPER
  - ln -s workspace.Cargo.toml Cargo.toml
  - echo ${TRAVIS_RUST_VERSION}
  - if [ "${TRAVIS_RUST_VERSION}" == "beta" ]; then
      echo "check code style";
      cargo fmt --package rust_swig -- --write-mode diff;
    fi
  - time cargo build -v --package rust_swig
  - time cargo test -v --package rust_swig
  - time cargo doc -v --package rust_swig
  - python ci_build_and_test.py
