language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
addons:
  apt:
    packages:
      - oracle-java8-set-default
script:
  - cd macroslib
  - cargo build -v
  - cargo test -v
  - cargo doc
  - cd ../jni_tests
  - cargo build -v
