language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-set-default
      - llvm-3.9-dev
      - libclang-3.9-dev
env: # specify the clang path for rust-bindgen
  - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib
script:
  - cd macroslib
  - cargo build -v
  - cargo test -v
  - cargo doc
  - cd ../jni_tests
  - cargo build -v
