dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
cache:
  - cargo
  - directories:
     - /home/travis/.cache/sccache
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-set-default
      - llvm-3.9-dev
      - libclang-3.9-dev
      - python3
      - build-essential
env: # specify the clang path for rust-bindgen
  - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib
before_script:
    - wget https://github.com/mozilla/sccache/releases/download/0.2.4/sccache-0.2.4-x86_64-unknown-linux-musl.tar.gz
    - tar -xzvf sccache-0.2.4-x86_64-unknown-linux-musl.tar.gz
    - mv sccache-0.2.4-x86_64-unknown-linux-musl/sccache ~/.cargo/bin
    - sccache --version
    - export RUSTC_WRAPPER=sccache
    - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f --vers 0.2.16 rustfmt-nightly;
      fi
    - cmake --version
    - export TAR="boost_1_56_0.tar.gz"
    - curl -L -o $TAR http://sourceforge.net/projects/boost/files/boost/1.56.0/$TAR/download
    - tar -xzf $TAR
    - export BOOST_ROOT=$PWD/boost_1_56_0
script:
  - echo $RUSTC_WRAPPER
  - ln -s workspace.Cargo.toml Cargo.toml
  - cd macroslib
  - echo ${TRAVIS_RUST_VERSION}
  - if [ "${TRAVIS_RUST_VERSION}" == "nightly" ]; then
      echo "check code style";
      cargo fmt -- --write-mode diff;
      cd ../jni_tests;
      cargo fmt -- --write-mode diff;
      cd ../android-example;
      cargo fmt -- --write-mode diff;
      cd ../macroslib;
    fi
  - cargo build -v
  - cargo test -v
  - cargo doc
  - cd ..
  - python3 ci_build_and_test.py
