dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
cache:
  timeout: 180
  directories:
    - /home/travis/.cargo
    - /home/travis/.cache/sccache
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-set-default
      - llvm-3.9-dev
      - libclang-3.9-dev
      - python3
      - build-essential
      - valgrind
env: # specify the clang path for rust-bindgen
  - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib
before_script:
    - wget https://github.com/mozilla/sccache/releases/download/0.2.5/sccache-0.2.5-x86_64-unknown-linux-musl.tar.gz
    - tar -xzvf sccache-0.2.5-x86_64-unknown-linux-musl.tar.gz
    - mv sccache-0.2.5-x86_64-unknown-linux-musl/sccache ~/.cargo/bin
    - sccache --version
    - du -s -c -h /home/travis/.cache/sccache
    - export RUSTC_WRAPPER=sccache
    - export SCCACHE_CACHE_SIZE=500M
    - if [ "$TRAVIS_RUST_VERSION" == "beta" ]; then
          rustup component add --toolchain beta rustfmt-preview;
      fi
    - cmake --version
    - export TAR="boost_1_56_0.tar.gz"
    - curl -L -o $TAR http://sourceforge.net/projects/boost/files/boost/1.56.0/$TAR/download
    - tar -xzf $TAR
    - export BOOST_ROOT=$PWD/boost_1_56_0
script:
  - echo $RUSTC_WRAPPER
  - ln -s workspace.Cargo.toml Cargo.toml
  - echo ${TRAVIS_RUST_VERSION}
  - if [ "${TRAVIS_RUST_VERSION}" == "beta" ]; then
      echo "check code style";
      cargo fmt --package rust_swig -- --write-mode diff;
    fi
  - time cargo build --package rust_swig
  - time cargo test --package rust_swig
  - time cargo doc --package rust_swig
  - python3 ci_build_and_test.py
  - du -s -c -h /home/travis/.cache/sccache
