dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
cache: cargo
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-set-default
      - llvm-3.9-dev
      - libclang-3.9-dev
      - python3
      - build-essential
env: # specify the clang path for rust-bindgen
  - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib
before_script:
    - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f --vers 0.2.16 rustfmt-nightly;
      fi
    - cmake --version
script:
  - ln -s workspace.Cargo.toml Cargo.toml
  - cd macroslib
  - echo ${TRAVIS_RUST_VERSION}
  - if [ "${TRAVIS_RUST_VERSION}" == "nightly" ]; then
      echo "check code style";
      cargo fmt -- --write-mode diff;
      cd ../jni_tests;
      cargo fmt -- --write-mode diff;
      cd ../android-example;
      cargo fmt -- --write-mode diff;
      cd ../macroslib;
    fi
  - cargo build -v
  - cargo test -v
  - cargo doc
  - cd ..
  - python3 ci_build_and_test.py
