[package]
name = "rust_swig"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]

[dependencies]
syntex = "0.43.0"
syntex_syntax = "0.43.0"
syntex_pos = "0.43.0"
aster = {version = "0.26.1", features=["with-syntex"]}