[package]
name = "android"
version = "0.0.1"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
build = "build.rs"

[lib]
name = "mobcore"
crate-type = ["cdylib"]

[dependencies]
log = "0.3"
log-panics = "1.1.0"
android_logger = "0.3.0"

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang-nursery/rust-bindgen", rev = "ce7e69bfbc5a6e47eb1d9ee4f0b43a5afeef0f31" }
syntex = "0.58.1"
rust_swig = { path = "../macroslib" }
